# Generated by Django 4.0.6 on 2022-09-25 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('archive_slug', models.SlugField(null=True)),
                ('archive_type', models.CharField(choices=[('ARTIST', 'Artist'), ('INSTITUTION', 'Institution'), ('COLLECTIVE', 'Collective')], default='ARTIST', max_length=20, verbose_name='type of archive')),
                ('private', models.BooleanField(default=True)),
                ('bio', models.CharField(max_length=600)),
                ('insta_link', models.URLField(blank=True, null=True)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('archive_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aword1', models.CharField(max_length=20)),
                ('aword2', models.CharField(max_length=20)),
                ('aword3', models.CharField(max_length=20)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('institution_name', models.CharField(max_length=50)),
                ('institution_website', models.URLField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('node_order_index', models.IntegerField(blank=True, default=0, editable=False)),
                ('archive', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='archival.archive')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('work_slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
                ('authors', models.CharField(blank=True, max_length=50, null=True)),
                ('classification', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.URLField(blank=True, max_length=50, null=True)),
                ('record_creator', models.CharField(blank=True, max_length=50, null=True)),
                ('cd1_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd1_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd2_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd2_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd3_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd3_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd4_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd4_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd5_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd5_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd6_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd6_value', models.CharField(blank=True, max_length=50, null=True)),
                ('cd7_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cd7_value', models.CharField(blank=True, max_length=50, null=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.archive')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.folder')),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('alt_text', models.CharField(max_length=60)),
                ('caption', models.CharField(max_length=60)),
                ('media', models.FileField(upload_to='documents/')),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.folder')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archival.work')),
            ],
        ),
    ]
