# Generated by Django 4.0.6 on 2022-07-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('node_order_index', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('work_slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1200)),
                ('authors', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=50)),
                ('record_creator', models.CharField(max_length=50)),
                ('cd1_name', models.CharField(max_length=50)),
                ('cd1_value', models.CharField(max_length=50)),
                ('cd2_name', models.CharField(max_length=50)),
                ('cd2_value', models.CharField(max_length=50)),
                ('cd3_name', models.CharField(max_length=50)),
                ('cd3_value', models.CharField(max_length=50)),
                ('cd4_name', models.CharField(max_length=50)),
                ('cd4_value', models.CharField(max_length=50)),
                ('cd5_name', models.CharField(max_length=50)),
                ('cd5_value', models.CharField(max_length=50)),
                ('cd6_name', models.CharField(max_length=50)),
                ('cd6_value', models.CharField(max_length=50)),
                ('cd7_name', models.CharField(max_length=50)),
                ('cd7_value', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstituionalArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('archive_slug', models.SlugField()),
                ('bio', models.CharField(max_length=600)),
                ('insta_link', models.URLField()),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('private', models.BooleanField()),
                ('archive_image', models.ImageField(upload_to='')),
                ('institution_name', models.CharField(max_length=50)),
                ('institution_website', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('archive_slug', models.SlugField()),
                ('bio', models.CharField(max_length=600)),
                ('insta_link', models.URLField()),
                ('fb_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('private', models.BooleanField()),
                ('archive_image', models.ImageField(upload_to='')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('aword1', models.CharField(max_length=20)),
                ('aword2', models.CharField(max_length=20)),
                ('aword3', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
